Repository appcircleio/appcircle-docusaurus, pull requests merged in 2024-05, with the labels that each got.

#438 #BE-2111 Added Monitoring Documentation Page
  docs/self-hosted-appcircle/configure-server/_appcircle-server-downtime-caution.mdx
  docs/self-hosted-appcircle/configure-server/_restart-appcircle-server.mdx
  docs/self-hosted-appcircle/configure-server/advanced-configuration/cache-size-configuration.md
  docs/self-hosted-appcircle/configure-server/monitoring.md
  docs/self-hosted-appcircle/install-server/docker.md
  docs/self-hosted-appcircle/install-server/podman.md
  docs/self-hosted-appcircle/install-server/pre-installation-checklist.md
Labels: in review, autoupdate

#468 #BE-2938 Updated 'Download' Links for Appcircle Server Packages
  docs/self-hosted-appcircle/install-server/docker.md
  docs/self-hosted-appcircle/install-server/podman.md
  docs/self-hosted-appcircle/update.md
Labels: autoupdate

#458 #BE-2938 Added Document Auto Updated and Downloader Script
  docs/self-hosted-appcircle/configure-server/auto-updating.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/network-access.md
  docs/self-hosted-appcircle/configure-server/minio-migration.md
  docs/self-hosted-appcircle/install-server/docker.md
  docs/self-hosted-appcircle/install-server/podman.md
  docs/self-hosted-appcircle/update.md
Labels: autoupdate

#465 [BE-3667] Added Meta Data Information doc
  docs/publish-module/publish-information/meta-data-information.md
Labels: autoupdate

#470 chore: Add store status feature to Publish module documentation
  docs/publish-module/binary-management/index.md
Labels: autoupdate

#186 #BE-2005 Added Install VM Script For Running In The Background
  docs/release-notes.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/network-access.md
  docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
Labels: autoupdate

#476 #BE-3700 Configure Server Index & Auto Update Proxy Caution
  docs/self-hosted-appcircle/configure-server/auto-updating.md
  docs/self-hosted-appcircle/configure-server/index.md
Labels: autoupdate

#481 Feature/BE-3167 Docs Update - AAB to APK on Testing Distribution page
  docs/distribute/create-or-select-a-distribution-profile.md
Labels: autoupdate

#457 Update Jira Comment with new input
  docs/release-notes.md
  docs/workflows/common-workflow-steps/jira-comment.md
  docs/workflows/common-workflow-steps/jira-component.md
  netlify.toml
Labels: autoupdate

#477 #BE-3700 Added Auto Update Info to Updating Page
  docs/self-hosted-appcircle/configure-server/minio-migration.md
  docs/self-hosted-appcircle/update.md
Labels: autoupdate

#473 #BE-3684 Added Disabling Monitoring Section
  docs/self-hosted-appcircle/configure-server/monitoring.md
Labels: autoupdate

#489 #BE-3108 Docs Update - Environment Variable Type Field Update
  docs/environment-variables/index.md
  docs/environment-variables/managing-variables.md
  docs/environment-variables/platform-specific-usage/using-environment-variables-in-android-projects.md
  docs/environment-variables/platform-specific-usage/using-environment-variables-in-ios-projects.md
Labels: autoupdate

#492 Added FAQ for Huawei AppGallery
  docs/account/my-organization/api-integrations/adding-huawei-api-key.md
  docs/best-practices/onboarding.md
  docs/intro.md
  docs/release-notes.md
Labels: documentation, enhancement, autoupdate

#491 Added FAQ to Google API Key
  docs/account/my-organization/api-integrations/adding-google-play-service-account.md
Labels: documentation, enhancement, autoupdate

#461 Snyk the component list and file name
  docs/workflows/android-specific-workflow-steps/app-post-processor.md
  docs/workflows/android-specific-workflow-steps/lint.md
Labels: documentation, autoupdate

#488 Added Get Approval via Email doc
  docs/publish-integrations/common-publish-integrations/_category_.json
  docs/publish-integrations/common-publish-integrations/get-approval-via-email.md
  docs/publish-integrations/common-publish-integrations/index.md
Labels: documentation, autoupdate

#487 [BE-3741]: Added update metadata doc
  docs/publish-integrations/ios-publish-integrations/index.md
  docs/publish-integrations/ios-publish-integrations/update-metadata-on-app-store-connect.md
Labels: autoupdate

#493 Feature/publish integration for ms intune
  docs/publish-integrations/common-publish-integrations/index.md
  docs/publish-integrations/common-publish-integrations/send-to-microsoft-intune.md
  docs/publish-module/index.md
  docs/publish-module/publish-flow/index.md
Labels: autoupdate

#494 #BE-3113 Docs Update - Notification Icon and Message Content Improvement
  docs/account/my-organization/notifications-and-communication/slack/slack-notifications.md
Labels: autoupdate

#496 BE-2922 Update Google Play Publish step doc
  docs/best-practices/onboarding.md
  docs/getting-started-with-appcircle.md
  docs/publish-integrations/android-publish-integrations/app-information-from-google-play.md
  docs/publish-integrations/android-publish-integrations/get-approval-from-google-play.md
  docs/publish-integrations/android-publish-integrations/index.md
  docs/publish-integrations/android-publish-integrations/publish-to-google-play.md
  docs/publish-integrations/android-publish-integrations/publish-to-huawei-appgallery.md
  docs/publish-integrations/android-publish-integrations/send-to-googleplay.md
  docs/publish-integrations/android-publish-integrations/send-to-huawei.md
  docs/release-notes.md
  docs/troubleshooting-faq/common-issues.md
  docs/workflows/common-workflow-steps/publish-release-notes.md
  netlify.toml
Labels: documentation, autoupdate
