Repository appcircleio/appcircle-docusaurus, pull requests merged in 2024-07, with the labels that each got.

#531 #BE-3984 Release Notes 3.19.0 Fixes
  docs/release-notes.md
Labels: autoupdate

#532 Feature/publish integration for ms intune
  docs/publish-integrations/common-publish-integrations/index.md
  docs/publish-integrations/common-publish-integrations/send-to-microsoft-intune.md
  docs/publish-integrations/common-publish-integrations/update-metadata-on-microsoft-intune.md
  docs/publish-integrations/ios-publish-integrations/index.md
  docs/publish-module/publish-settings/index.md
Labels: autoupdate

#534 Fixed some missing docs
  docs/publish-module/creating-publish-profiles/index.md
  docs/publish-module/index.md
  docs/publish-module/publish-settings/index.md
Labels: autoupdate

#519 #BE-3203 Break down the FAQs into relevant sections
  docs/build/manage-the-connections/adding-a-build-profile/connecting-to-github.md
  docs/build/manage-the-connections/adding-a-build-profile/connecting-to-private-repository-via-ssh.md
  docs/build/manage-the-connections/adding-a-build-profile/index.md
  docs/build/platform-build-guides/building-android-applications/index.md
  docs/build/platform-build-guides/building-flutter-applications/building-flutter-applications.md
  docs/build/platform-build-guides/building-ios-applications.md
  docs/build/platform-build-guides/building-react-native-applications.md
  docs/build/platform-build-guides/index.md
  docs/build/post-build-operations/after-a-build.md
  docs/continuous-testing/android-testing/running-android-unit-tests.md
  docs/distribute/index.md
  docs/enterprise-appstore/index.md
  docs/publish-module/publish-information/resign-binary.md
  docs/release-notes.md
  docs/troubleshooting-faq/_category_.json
  docs/troubleshooting-faq/common-issues.md
  docs/troubleshooting-faq/enterprise-app-store-faq.md
  docs/troubleshooting-faq/index.md
  docs/workflows/ios-specific-workflow-steps/xcodebuild-for-devices.md
Labels: autoupdate

#535 [BE-3747] add Azure AD documentation for SSO Mapping
  docs/account/my-organization/sso-providers-configuration/auth-openid.md
  docs/account/my-organization/sso-providers-configuration/auth-saml.md
  docs/account/my-organization/sso-providers-configuration/azure-saml.md
  docs/account/my-organization/sso-providers-configuration/okta-openid.md
  docs/account/my-organization/sso-providers-configuration/okta-saml.md
  docs/account/my-organization/sso-providers-configuration/single-sign-on.md
Labels: autoupdate

#536 Added FAQ for generate APK with AAB
  docs/workflows/android-specific-workflow-steps/android-build.md
Labels: documentation, autoupdate

#539 duplicated environment definitions fixed
  docs/publish-integrations/common-publish-integrations/send-to-microsoft-intune.md
Labels: autoupdate

#540 #BE-4008 Release Notes 3.19.1
  docs/release-notes.md
Labels: autoupdate

#537 #BE-3682 Webhooks - Notifications missing keywords
  docs/account/index.md
  docs/account/my-organization/notifications-and-communication/index.md
  docs/account/my-organization/notifications-and-communication/teams-notifications.md
  docs/account/my-organization/webhooks.md
Labels: autoupdate

#541 #BE-4016 Release Notes 3.19.1 Update
  docs/release-notes.md
Labels: autoupdate

#530 #BE-3960 Carry the main FAQ of Appcircle inside Distribution Docs
  docs/distribute/testing-management/testing-groups.md
Labels: Draft, autoupdate

#542 #BE-4012 Documentation SEO Issues [Semrush]
  docs/account/my-organization/team-activity-log.md
  docs/account/my-organization/webhooks.md
  docs/marketplace/fastlane/enterprise-store/index.md
  docs/marketplace/fastlane/testing-distribution/index.md
  docs/marketplace/jenkins/enterprise-store/index.md
  docs/marketplace/visual-studio-marketplace/testing-distribution/index.md
  docs/publish-integrations/common-publish-integrations/custom-script.md
  docs/workflows/android-specific-workflow-steps/app-post-processor.md
Labels: autoupdate

#510 #BE-3839 New Redis Subdomain Update
  docs/release-notes.md
  docs/self-hosted-appcircle/configure-server/_redis-domain-caution.mdx
  docs/self-hosted-appcircle/configure-server/auto-updating.md
  docs/self-hosted-appcircle/configure-server/enterprise-store.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/login-configuration.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/network-access.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/ssl-configuration.md
  docs/self-hosted-appcircle/configure-server/minio-migration.md
  docs/self-hosted-appcircle/install-server/docker.md
  docs/self-hosted-appcircle/install-server/podman.md
  docs/self-hosted-appcircle/install-server/pre-installation-checklist.md
  docs/self-hosted-appcircle/self-hosted-runner/_configure-for-self-hosted.mdx
  docs/self-hosted-appcircle/self-hosted-runner/_new_runner-old_server-redis-caution.mdx
  docs/self-hosted-appcircle/self-hosted-runner/cloud-providers/aws.md
  docs/self-hosted-appcircle/self-hosted-runner/installation.md
  docs/self-hosted-appcircle/self-hosted-runner/runner-vm-setup.md
  docs/self-hosted-appcircle/self-hosted-runner/update.md
  docs/self-hosted-appcircle/update.md
Labels: autoupdate

#543 Added warning about version name format
  docs/versioning/android-version.md
Labels: autoupdate

#544 #BE-4019 ReadME Updates
  README.md
Labels: autoupdate

#545 #BE-4041 3.19.1 New Updates
  docs/release-notes.md
Labels: autoupdate

#548 #BE-4049 Remove FAQ Link From Onboarding
  docs/best-practices/onboarding.md
Labels: autoupdate

#549 added robots file
  static/robots.txt
Labels: autoupdate

#550 #BE-4052 Release Notes 3.19.1 Xcode Update
  docs/release-notes.md
Labels: autoupdate

#554 #BE-4053 Front End Update Release Notes - July 12th
  docs/release-notes.md
Labels: autoupdate

#547 #BE-3109 Build Profile Branch List Filter for Build Status
  docs/build/build-process-management/build-profile-branch-operations.md
Labels: autoupdate

#558 #BE-4072 Docs - Organization Members Search Filter
  docs/account/my-organization/my-organization.md
Labels: autoupdate

#553 #BE-4054 Docs - Separating Appcircle CLI and API
  docs/appcircle-api/api-authentication.md
  docs/appcircle-api/cli-authentication.md
  docs/appcircle-api/index.md
Labels: autoupdate

#551 #BE-3106 Publish Profile Filter for Statuses
  docs/publish-module/binary-management/index.md
Labels: autoupdate

#556 BE-4060 Docs - Multiple Provisioning Profile Upload / Delete Update
  docs/signing-identities/apple-profiles.md
Labels: autoupdate

#559 #BE-4073 Docs - Switching Organizations Update
  docs/account/my-organization/my-organization.md
Labels: autoupdate

#524 #BE-3008 Added Appcircle DMZ Server Document
  docs/release-notes.md
  docs/self-hosted-appcircle/configure-server/_firewalld-configuration.mdx
  docs/self-hosted-appcircle/configure-server/_linger-option.mdx
  docs/self-hosted-appcircle/configure-server/_podman-netavark-configuration.mdx
  docs/self-hosted-appcircle/configure-server/_socat-configuration.mdx
  docs/self-hosted-appcircle/configure-server/_swap-configuration.mdx
  docs/self-hosted-appcircle/configure-server/_ufw-configuration.mdx
  docs/self-hosted-appcircle/configure-server/advanced-configuration/index.md
  docs/self-hosted-appcircle/configure-server/advanced-configuration/store-dist-dmz.md
  docs/self-hosted-appcircle/configure-server/auto-updating.md
  docs/self-hosted-appcircle/configure-server/integrations-and-access/network-access.md
  docs/self-hosted-appcircle/configure-server/offline-installation.md
  docs/self-hosted-appcircle/index.md
  docs/self-hosted-appcircle/install-server/podman.md
  docs/self-hosted-appcircle/update.md
Labels: autoupdate

#557 Updated build reserved env var
  docs/environment-variables/appcircle-specific-environment-variables.md
Labels: autoupdate

#561 Added warn about dynamic version on Gradle
  docs/versioning/android-version.md
Labels: documentation, autoupdate

#564 #BE-4082 Docs - Enterprise Store Updates
  docs/enterprise-appstore/enterprise-app-store-setup/configure-ent-profile.md
  docs/enterprise-appstore/enterprise-app-store-setup/customize-ent-store.md
Labels: autoupdate

#552 [BE-4051]: All permissions have been changed and added detailed tables
  docs/account/my-organization/role-management.md
Labels: autoupdate

#568 Added new reject and cancel feature for publish doc
  docs/publish-module/publish-information/cancel-submission.md
  docs/publish-module/publish-information/delete.md
  docs/publish-module/publish-information/index.md
  docs/publish-module/publish-information/reject-binary.md
  docs/signing-identities/apple-profiles.md
Labels: autoupdate

#563 feat: app center migration cli tool
  docs/appcircle-api/appcenter-migration-tool.md
Labels: autoupdate

#570 Added new environment varianle to publish
  docs/publish-module/publish-variables/index.md
Labels: documentation, autoupdate

#571 Fixed some logical errors
  docs/account/my-organization/role-management.md
  docs/appcircle-api/appcenter-migration-tool.md
Labels: autoupdate

#569 #BE-4071 Testing Distribution Docs Improvement
  docs/build/post-build-operations/after-a-build.md
  docs/distribute/create-or-select-a-distribution-profile.md
  docs/distribute/downloading-binaries.md
  docs/distribute/platform-specific-guidance/_category_.json
  docs/distribute/reports/index.md
  docs/distribute/testing-groups.md
  docs/distribute/testing-management/_category_.json
  docs/distribute/testing-management/downloading-binaries.md
  docs/distribute/testing-management/index.md
  docs/release-notes.md
Labels: autoupdate

#567 #BE-4118 Release Notes 3.20.0
  docs/account/my-organization/role-management.md
  docs/release-notes.md
Labels: autoupdate

#574 New fix/be 4051
  docs/account/my-organization/role-management.md
Labels: autoupdate

#575 add npm package link
  docs/appcircle-api/appcenter-migration-tool.md
Labels: autoupdate

#578 change title orders
  docs/appcircle-api/appcenter-migration-tool.md
Labels: autoupdate

#579 #BE-4150 Migration Tool Update
  docs/appcircle-api/index.md
Labels: autoupdate
